// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tradier.Data;

#nullable disable

namespace Tradier.Data.Migrations
{
    [DbContext(typeof(TradierDbContext))]
    partial class TradierDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Tradier.Entities.Models.Balances", b =>
                {
                    b.Property<int>("sId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("sId"));

                    b.Property<string>("AccountNumber")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AccountType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CashId")
                        .HasColumnType("int");

                    b.Property<float>("ClosePL")
                        .HasColumnType("real");

                    b.Property<float>("CurrentRequirement")
                        .HasColumnType("real");

                    b.Property<DateTime>("DateInserted")
                        .HasColumnType("datetime2");

                    b.Property<int>("Equity")
                        .HasColumnType("int");

                    b.Property<float>("LongMarketValue")
                        .HasColumnType("real");

                    b.Property<int>("MarginId")
                        .HasColumnType("int");

                    b.Property<float>("MarketValue")
                        .HasColumnType("real");

                    b.Property<float>("OpenPL")
                        .HasColumnType("real");

                    b.Property<float>("OptionLongValue")
                        .HasColumnType("real");

                    b.Property<float>("OptionRequirement")
                        .HasColumnType("real");

                    b.Property<float>("OptionShortValue")
                        .HasColumnType("real");

                    b.Property<int>("PatternDayTraderId")
                        .HasColumnType("int");

                    b.Property<float>("PendingCash")
                        .HasColumnType("real");

                    b.Property<int>("PendingOrdersCount")
                        .HasColumnType("int");

                    b.Property<float>("ShortMarketValue")
                        .HasColumnType("real");

                    b.Property<float>("StockLongValue")
                        .HasColumnType("real");

                    b.Property<float>("TotalCash")
                        .HasColumnType("real");

                    b.Property<float>("TotalEquity")
                        .HasColumnType("real");

                    b.Property<int>("UnclearedFunds")
                        .HasColumnType("int");

                    b.HasKey("sId");

                    b.HasIndex("AccountNumber")
                        .IsUnique()
                        .HasFilter("[AccountNumber] IS NOT NULL");

                    b.HasIndex("CashId")
                        .IsUnique();

                    b.HasIndex("MarginId")
                        .IsUnique();

                    b.HasIndex("PatternDayTraderId")
                        .IsUnique();

                    b.ToTable("Balances");
                });

            modelBuilder.Entity("Tradier.Entities.Models.Cash", b =>
                {
                    b.Property<int>("sId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("sId"));

                    b.Property<float>("CashAvailable")
                        .HasColumnType("real");

                    b.Property<int>("Sweep")
                        .HasColumnType("int");

                    b.Property<float>("UnsettledFunds")
                        .HasColumnType("real");

                    b.HasKey("sId");

                    b.ToTable("Cash");
                });

            modelBuilder.Entity("Tradier.Entities.Models.Leg", b =>
                {
                    b.Property<int>("DatabaseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DatabaseId"));

                    b.Property<float>("AvgFillPrice")
                        .HasColumnType("real");

                    b.Property<string>("Class")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DatabaseOrderId")
                        .HasColumnType("int");

                    b.Property<string>("Duration")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("ExecQuantity")
                        .HasColumnType("real");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<float>("LastFillPrice")
                        .HasColumnType("real");

                    b.Property<float>("LastFillQuantity")
                        .HasColumnType("real");

                    b.Property<string>("OptionSymbol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.Property<float>("Quantity")
                        .HasColumnType("real");

                    b.Property<float>("RemainingQuantity")
                        .HasColumnType("real");

                    b.Property<string>("Side")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DatabaseId");

                    b.HasIndex("DatabaseOrderId");

                    b.ToTable("Leg");
                });

            modelBuilder.Entity("Tradier.Entities.Models.Margin", b =>
                {
                    b.Property<int>("sId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("sId"));

                    b.Property<int>("FedCall")
                        .HasColumnType("int");

                    b.Property<int>("MaintenanceCall")
                        .HasColumnType("int");

                    b.Property<float>("OptionBuyingPower")
                        .HasColumnType("real");

                    b.Property<float>("StockBuyingPower")
                        .HasColumnType("real");

                    b.Property<int>("StockShortValue")
                        .HasColumnType("int");

                    b.Property<int>("Sweep")
                        .HasColumnType("int");

                    b.HasKey("sId");

                    b.ToTable("Margin");
                });

            modelBuilder.Entity("Tradier.Entities.Models.Order", b =>
                {
                    b.Property<int>("DatabaseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DatabaseId"));

                    b.Property<float>("AvgFillPrice")
                        .HasColumnType("real");

                    b.Property<string>("Class")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Duration")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("ExecQuantity")
                        .HasColumnType("real");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<float>("LastFillPrice")
                        .HasColumnType("real");

                    b.Property<float>("LastFillQuantity")
                        .HasColumnType("real");

                    b.Property<int>("NumLegs")
                        .HasColumnType("int");

                    b.Property<string>("OptionSymbol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.Property<float>("Quantity")
                        .HasColumnType("real");

                    b.Property<float>("RemainingQuantity")
                        .HasColumnType("real");

                    b.Property<string>("Side")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Strategy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DatabaseId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Tradier.Entities.Models.PatternDayTrader", b =>
                {
                    b.Property<int>("sId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("sId"));

                    b.Property<int>("FedCall")
                        .HasColumnType("int");

                    b.Property<int>("MaintenanceCall")
                        .HasColumnType("int");

                    b.Property<float>("OptionBuyingPower")
                        .HasColumnType("real");

                    b.Property<float>("StockBuyingPower")
                        .HasColumnType("real");

                    b.Property<int>("StockShortValue")
                        .HasColumnType("int");

                    b.HasKey("sId");

                    b.ToTable("PatternDayTrader");
                });

            modelBuilder.Entity("Tradier.Entities.Models.SLeg", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BuySell")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("CostBasis")
                        .HasColumnType("real");

                    b.Property<DateTime>("Expry")
                        .HasColumnType("datetime2");

                    b.Property<string>("OpenClose")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OptionSymbol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PutCall")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("QuantityExecuted")
                        .HasColumnType("real");

                    b.Property<float>("QuantityOrdered")
                        .HasColumnType("real");

                    b.Property<float>("RatioThisLegToTotalPNL")
                        .HasColumnType("real");

                    b.Property<float>("RatioThisLegToTotalQty")
                        .HasColumnType("real");

                    b.Property<float>("RemainingQuantity")
                        .HasColumnType("real");

                    b.Property<int>("Strike")
                        .HasColumnType("int");

                    b.Property<float>("ThisFillPrice")
                        .HasColumnType("real");

                    b.Property<float>("ThisFillQuantity")
                        .HasColumnType("real");

                    b.Property<string>("Underlying")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("brokerId")
                        .HasColumnType("int");

                    b.Property<int>("brokerOrderId")
                        .HasColumnType("int");

                    b.Property<int>("orderId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("orderId");

                    b.ToTable("SLeg");
                });

            modelBuilder.Entity("Tradier.Entities.Models.SOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreditDebit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ExpryDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("NumContracts")
                        .HasColumnType("int");

                    b.Property<int>("NumLegs")
                        .HasColumnType("int");

                    b.Property<string>("OpenClosed")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.Property<int?>("StradeFlyId")
                        .HasColumnType("int");

                    b.Property<string>("Strategy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TOSString")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("brokerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("SOrders");
                });

            modelBuilder.Entity("Tradier.Entities.Models.Balances", b =>
                {
                    b.HasOne("Tradier.Entities.Models.Cash", "Cash")
                        .WithOne()
                        .HasForeignKey("Tradier.Entities.Models.Balances", "CashId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tradier.Entities.Models.Margin", "Margin")
                        .WithOne()
                        .HasForeignKey("Tradier.Entities.Models.Balances", "MarginId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tradier.Entities.Models.PatternDayTrader", "PatternDayTrader")
                        .WithOne()
                        .HasForeignKey("Tradier.Entities.Models.Balances", "PatternDayTraderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cash");

                    b.Navigation("Margin");

                    b.Navigation("PatternDayTrader");
                });

            modelBuilder.Entity("Tradier.Entities.Models.Leg", b =>
                {
                    b.HasOne("Tradier.Entities.Models.Order", null)
                        .WithMany("Legs")
                        .HasForeignKey("DatabaseOrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Tradier.Entities.Models.SLeg", b =>
                {
                    b.HasOne("Tradier.Entities.Models.SOrder", null)
                        .WithMany("SLegs")
                        .HasForeignKey("orderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Tradier.Entities.Models.Order", b =>
                {
                    b.Navigation("Legs");
                });

            modelBuilder.Entity("Tradier.Entities.Models.SOrder", b =>
                {
                    b.Navigation("SLegs");
                });
#pragma warning restore 612, 618
        }
    }
}
